### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [naralynne/prj-rev-bwfs-dasmoto#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project. The page looks great and you've done an excellent job keeping the project folder organized using a separate resources folder. Nice work using divs to help structure the content in the html as well!

Behind the scenes, make sure to use classes for any names that you want to use more than once in the html. Ids are unique and should only be used once on a page. Also, try to keep your indentation as consistent as possible. Clean, readable code is crucial and only becomes more so as your projects grow in size and complexity.

As a next step try saving your image files locally to an images folder inside of resources and then use relative file paths to link to those from your html and css. The link to css on line 5 of your html is a great example and more info can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/).

Have fun and keep up the good work!

**Comment by naralynne** [comment]
Appreciate all of your feedback! Thanks!
